package:
  name: eidl
  version: "{{ GIT_DESCRIBE_TAG }}"

source:
  git_url: https://github.com/haasad/EcoInventDownLoader.git
  git_rev: master

build:
  noarch: python
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  entry_points:
      - get_ecoinvent = eidl.core:get_ecoinvent_cli

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - brightway2
    - requests
    - beautifulsoup4
    - py7zr
    - appdirs

test:
  imports:
    - eidl

about:
  home: https://github.com/haasad/EcoInventDownLoader
  license: MIT
  license_family: MIT
  summary: EcoInventDownLoader (eidl)
  description: |
    Download, unpack and import ecoinvent into your brightway2 project in one simple step.
    More details and installation instructions can be found on [github](https://github.com/haasad/EcoInventDownLoader)
