name: conda-release

on:
  release:
    types:
      - created

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - uses: actions/checkout@v2
      - name: Set up miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.8
          activate-environment: build
          environment-file: .github/environment-build.yml
      - name: Build conda package
        shell: bash -l {0}
        run: |
          conda build ./conda-recipe/
      - name: Upload to haasad conda channel
        shell: bash -l {0}
        run: |
          anaconda -t ${{ secrets.CONDA_TOKEN }} upload \
          /usr/share/miniconda/envs/test/conda-bld/noarch/*.tar.bz2
